[build-system]
requires = ["hatch"]
build-backend = "hatchling.build"

[project]
name = "pybop"
version = "26.3"
authors = [
  {name = "The PyBOP Team"},
]
maintainers = [
  {name = "The PyBOP Team"},
]
description = "Python Battery Optimisation and Parameterisation"
readme = {file = "README.md", content-type = "text/markdown"}
license = "BSD-3-Clause"
license-files = ["LICENSE"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
]
# When updating the Python version ranges, please also bump the Python
# versions in the tests in nightly_dependency_tests.yml as appropriate
requires-python = ">=3.10, <3.15"
dependencies = [
    "pybamm[plot]>=26.3.0",
    "numpy>=1.26",
    "scipy>=1.12",
    "pints>=0.6.0",
    "pebble",
    "polars>=1.18.0",
]

[project.optional-dependencies]
plotly = ["plotly>=6"]
scienceplots = ["SciencePlots>=2.2"]
salib = ["SALib>=1.5"]
scifem = [
  "scikit-fem>=8.1.0" # scikit-fem is a dependency for the multi-dimensional pybamm models
]
bpx = [
    "bpx>=0.5, <0.6",
]
ep-bolfi = [
    "GPy>=1.13.2; python_version < '3.13'",
    "ep-bolfi>=3.0.2; python_version < '3.13'"
]
pyprobe = [
  "PyProBE-Data>=2.6.0;python_version >= '3.11' and python_version < '3.13'"
]
all = ["pybop[plotly,scienceplots,salib,scifem,bpx,pyprobe,ep-bolfi]"]

[dependency-groups]
docs = [
    "pydata-sphinx-theme",
    "sphinx>=6",
    "sphinx-autobuild",
    "sphinx-autoapi",
    "sphinx-automodapi",
    "sphinx_copybutton",
    "sphinx_favicon",
    "sphinx_design",
    "myst-parser",
]
dev = [
    "nox[uv]",
    "nbmake",
    "pre-commit",
    "pytest>=6",
    "pytest-cov",
    "pytest-mock",
    "pytest-xdist",
    "ruff",
]

[tool.hatch.build.targets.sdist]
exclude = [
  "papers/",
  "tests/",
  "docs/",
  "assets/",
  "scripts/",
  "noxfile.py",
  "conftest.py",
  "CONTRIBUTING.md",
]

# the wheel additionally excludes files that are not needed for installation, such
#as the changelog and citation files, and the examples. those are present in the sdist.
[tool.hatch.build.targets.wheel]
exclude = [
  "papers/",
  "tests/",
  "docs/",
  "assets/",
  "scripts/",
  "examples/",
  "noxfile.py",
  "conftest.py",
  "CONTRIBUTING.md",
  "CHANGELOG.md",
  "CITATION.cff",
]

[project.urls]
Homepage = "https://github.com/pybop-team/PyBOP"
Documentation = "https://pybop-docs.readthedocs.io"
Repository = "https://github.com/pybop-team/PyBOP"
Releases = "https://github.com/pybop-team/PyBOP/releases"
Changelog = "https://github.com/pybop-team/PyBOP/blob/develop/CHANGELOG.md"

[tool.pytest.ini_options]
addopts = "--showlocals -v -n auto"

[tool.ruff]
extend-include = ["*.ipynb"]
extend-exclude = ["__init__.py"]
fix = true

[tool.ruff.lint]
select = [
    "A",    # flake8-builtins: Check for Python builtins being used as variables or parameters
    "B",    # flake8-bugbear: Find likely bugs and design problems
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes: Detect various errors by parsing the source file
    "I",    # isort: Check and enforce import ordering
    "ISC",  # flake8-implicit-str-concat: Check for implicit string concatenation
    "TID",  # flake8-tidy-imports: Validate import hygiene
    "UP",   # pyupgrade: Automatically upgrade syntax for newer versions of Python
    "SLF001",  # flake8-string-format: Check for private object name access
]

ignore = ["E501","E741"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["SLF001"]
"**.ipynb" = ["E402", "E703"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.coverage.run]
source = ["pybop"]
omit = [
    "*/tests/*",
    "tests/*",
    "*/test_*",
    "test_*"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError"
]
